--ModConfig
    TUNING.MERMHAT_PERISH = GetModConfigData("mermhat_perish")
    TUNING.MERMKING_EXCHANGERATE = GetModConfigData("mermking_rate")
    TUNING.MERMGUARD_BEFRIENDABLE = GetModConfigData("mermguard_friends")
    TUNING.MERM_SANITYAURA = GetModConfigData("merm_sanity")
    TUNING.MERM_SHARETARGETS = GetModConfigData("merm_united")

--Merm
    TUNING.MERM_DAMAGE = 30
    TUNING.MERM_DAMAGE_KINGBONUS = 40
    TUNING.MERM_HEALTH = 250
    TUNING.MERM_HEALTH_KINGBONUS = 280

    TUNING.MERM_ATTACK_PERIOD = 3
    TUNING.MERM_DEFEND_DIST = 30
    TUNING.MERM_TARGET_DIST = 10
    TUNING.MERM_RUN_SPEED = 8
    TUNING.MERM_WALK_SPEED = 3

    TUNING.MERM_LOYALTY_MAXTIME = 3 * 480
    TUNING.MERM_LOYALTY_PER_HUNGER = 480/25
    TUNING.MERM_MAX_TARGET_SHARES = 5
    TUNING.MERM_SHARE_TARGET_DIST = 40

--Mermguard
    TUNING.PUNY_MERM_DAMAGE = 20
    TUNING.MERM_GUARD_DAMAGE = 50
    TUNING.PUNY_MERM_HEALTH = 200
    TUNING.MERM_GUARD_HEALTH = 330

    TUNING.MERM_GUARD_ATTACK_PERIOD = 3
    TUNING.MERM_GUARD_DEFEND_DIST = 40
    TUNING.MERM_GUARD_TARGET_DIST = 15
    TUNING.MERM_GUARD_RUN_SPEED = 8
    TUNING.MERM_GUARD_WALK_SPEED = 3

    TUNING.MERM_GUARD_LOYALTY_MAXTIME = 3 * 480
    TUNING.MERM_GUARD_LOYALTY_PER_HUNGER = 480/25
    TUNING.MERM_GUARD_MAX_TARGET_SHARES = 8
    TUNING.MERM_GUARD_SHARE_TARGET_DIST = 60
